services:
  - type: web
    name: kyc-backend
    env: docker
    plan: starter
    autoDeploy: true
    healthCheckPath: /healthz

    envVars:
      - key: ENVIRONMENT
        value: production
      - key: SMTP_HOST
        sync: false
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: DATABASE_URL
        sync: false
